import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: '开始使用',
      collapsed: false,
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/nix-setup',
        'getting-started/updating',
        'getting-started/learning-path',
      ],
    },
    {
      type: 'category',
      label: '使用 Hermes',
      collapsed: false,
      items: [
        'user-guide/cli',
        'user-guide/configuration',
        'user-guide/sessions',
        'user-guide/security',
        'user-guide/docker',
        'user-guide/profiles',
      ],
    },
    {
      type: 'category',
      label: '功能特性',
      collapsed: false,
      items: [
        'user-guide/features/tools',
        'user-guide/features/skills',
        'user-guide/features/memory',
        'user-guide/features/context-files',
        'user-guide/features/personality',
        'user-guide/features/skins',
        'user-guide/features/cron',
        'user-guide/features/delegation',
        'user-guide/features/code-execution',
        'user-guide/features/hooks',
        'user-guide/features/voice-mode',
        'user-guide/features/browser',
        'user-guide/features/vision',
        'user-guide/features/image-generation',
        'user-guide/features/tts',
        'user-guide/features/batch-processing',
        'user-guide/features/rl-training',
        'user-guide/skills/godmode',
      ],
    },
    {
      type: 'category',
      label: '消息平台',
      collapsed: false,
      items: [
        'user-guide/messaging/index',
        'user-guide/messaging/telegram',
        'user-guide/messaging/discord',
        'user-guide/messaging/slack',
        'user-guide/messaging/whatsapp',
        'user-guide/messaging/signal',
        'user-guide/messaging/email',
        'user-guide/messaging/homeassistant',
        'user-guide/messaging/mattermost',
        'user-guide/messaging/matrix',
        'user-guide/messaging/dingtalk',
        'user-guide/messaging/feishu',
        'user-guide/messaging/wecom',
        'user-guide/messaging/open-webui',
        'user-guide/messaging/webhooks',
      ],
    },
    {
      type: 'category',
      label: '集成',
      collapsed: false,
      items: [
        'user-guide/features/api-server',
        'user-guide/features/acp',
        'user-guide/features/mcp',
        'user-guide/features/honcho',
        'user-guide/features/provider-routing',
        'user-guide/features/fallback-providers',
      ],
    },
    {
      type: 'category',
      label: '指南与教程',
      collapsed: false,
      items: [
        'guides/tips',
        'guides/daily-briefing-bot',
        'guides/team-telegram-assistant',
        'guides/python-library',
        'guides/use-mcp-with-hermes',
        'guides/use-soul-with-hermes',
        'guides/use-voice-mode-with-hermes',
      ],
    },
    {
      type: 'category',
      label: '开发者指南',
      collapsed: false,
      items: [
        'developer-guide/architecture',
        'developer-guide/agent-loop',
        'developer-guide/provider-runtime',
        'developer-guide/adding-providers',
        'developer-guide/prompt-assembly',
        'developer-guide/context-compression-and-caching',
        'developer-guide/gateway-internals',
        'developer-guide/session-storage',
        'developer-guide/tools-runtime',
        'developer-guide/acp-internals',
        'developer-guide/trajectory-format',
        'developer-guide/cron-internals',
        'developer-guide/environments',
        'developer-guide/adding-tools',
        'developer-guide/creating-skills',
        'developer-guide/extending-the-cli',
        'developer-guide/contributing',
      ],
    },
    {
      type: 'category',
      label: '参考资料',
      collapsed: false,
      items: [
        'reference/cli-commands',
        'reference/slash-commands',
        'reference/tools-reference',
        'reference/toolsets-reference',
        'reference/mcp-config-reference',
        'reference/skills-catalog',
        'reference/optional-skills-catalog',
        'reference/profile-commands',
        'reference/environment-variables',
        'reference/faq',
      ],
    },
  ],
};

export default sidebars;
